services:
  airsensor:
    build: .
    privileged: true
    command: ['python', '-u', 'main.py']
    volumes:
      - ./air_sensor.py:/usr/src/app/air_sensor.py
      - ./touch_sensor.py:/usr/src/app/touch_sensor.py
      - ./light_sensor.py:/usr/src/app/light_sensor.py
      - ./index.html:/usr/src/app/index.html
      - ./main.py:/usr/src/app/main.py
    ports:
      - 8080:8080